In [4]:
import pandas as pd

GROUPBY-->

In [6]:
var = pd.DataFrame({"Name":["e","d","a","f","c","b","a","e","f"],
                    "sub_1":[12,13,14,15,16,17,18,19,20],
                    "sub_2":[22,23,24,25,26,27,28,29,30],
                    "sub_3":[32,33,34,35,36,37,38,39,40],
                    "sub_4":[42,43,44,45,46,47,48,49,50]})
var

  Name  sub_1  sub_2  sub_3  sub_4
0    e     12     22     32     42
1    d     13     23     33     43
2    a     14     24     34     44
3    f     15     25     35     45
4    c     16     26     36     46
5    b     17     27     37     47
6    a     18     28     38     48
7    e     19     29     39     49
8    f     20     30     40     50

In [10]:
#group of same kind of data
var_New = var.groupby("Name")
var_New
for x,y in var_New: #used for printing!!
    print(x)
    print(y)
    print() #to get the space

a
  Name  sub_1  sub_2  sub_3  sub_4
2    a     14     24     34     44
6    a     18     28     38     48

b
  Name  sub_1  sub_2  sub_3  sub_4
5    b     17     27     37     47

c
  Name  sub_1  sub_2  sub_3  sub_4
4    c     16     26     36     46

d
  Name  sub_1  sub_2  sub_3  sub_4
1    d     13     23     33     43

e
  Name  sub_1  sub_2  sub_3  sub_4
0    e     12     22     32     42
7    e     19     29     39     49

f
  Name  sub_1  sub_2  sub_3  sub_4
3    f     15     25     35     45
8    f     20     30     40     50

In [11]:
var_New.get_group("a") # to get specific same kind of group

  Name  sub_1  sub_2  sub_3  sub_4
2    a     14     24     34     44
6    a     18     28     38     48

In [15]:
var_New.min()
var_New.max()
var_New.mean()

      sub_1  sub_2  sub_3  sub_4
Name
a        14     24     34     44
b        17     27     37     47
c        16     26     36     46
d        13     23     33     43
e        12     22     32     42
f        15     25     35     45

In [18]:
li = list(var_New) #used to convert in the form of list!!!
li #study the function of list!!

[('a',
    Name  sub_1  sub_2  sub_3  sub_4
  2    a     14     24     34     44
  6    a     18     28     38     48),
 ('b',
    Name  sub_1  sub_2  sub_3  sub_4
  5    b     17     27     37     47),
 ('c',
    Name  sub_1  sub_2  sub_3  sub_4
  4    c     16     26     36     46),
 ('d',
    Name  sub_1  sub_2  sub_3  sub_4
  1    d     13     23     33     43),
 ('e',
    Name  sub_1  sub_2  sub_3  sub_4
  0    e     12     22     32     42
  7    e     19     29     39     49),
 ('f',
    Name  sub_1  sub_2  sub_3  sub_4
  3    f     15     25     35     45
  8    f     20     30     40     50)]