In [13]:
import pandas as pd

csv_1=pd.read_csv("C:\\Users\\91742\\OneDrive\\Desktop\\ds_august\\Pandas\\Test_new2.csv")
print(csv_1)

    Index             Suburb               City  Postcode   Longitude  \
0       1       Freemans Bay           Auckland    1011.0  174.748652
1       2          Nightcaps          Southland    9630.0  168.028823
2       3          Northcote        North Shore     627.0  174.755505
3       4           Bay View             Napier    4104.0  176.871662
4       5          Parklands       Christchurch    8083.0  172.705997
5       6      Hamilton East           Hamilton    3216.0  175.305496
6       7           Te Kuiti            Waitomo    3910.0         NaN
7       8            Opaheke           Papakura    2113.0  174.947631
8       9  North East Valley            Dunedin    9010.0  170.527081
9      10         Whangamata  Thames-Coromandel    3620.0  175.883257
10     11         Algies Bay             Rodney     920.0  174.745447
11     12          Henderson          Waitakere     610.0         NaN
12     13            Atawhai             Nelson    7010.0  173.326718
13     14                NaN                NaN       NaN         NaN
14     15            Frimley           Hastings    4120.0  176.832406
15     16        Harrowfield           Hamilton    3210.0  175.266597
16     17            Tapanui             Clutha    9522.0         NaN
17     18            Tokoroa      South Waikato    3420.0  175.869172
18     19             Thames  Thames-Coromandel    3500.0  175.547120

     Latitude                                Full Address
0  -36.855732       Picton Street, Freemans Bay, Auckland
1  -45.970300           Lyne Street, Nightcaps, Southland
2         NaN      McBreen Avenue, Northcote, North Shore
3  -39.440389     Ferguson Street South, Bay View, Napier
4  -43.472699       Forest Drive, Parklands, Christchurch
5  -37.781657          Rochford Court, Hamilton, Hamilton
6  -38.330973         Alexandra Street, Te Kuiti, Waitomo
7  -37.077401             Rhonda Place, Opaheke, Papakura
8  -45.846837   Selwyn Street, North East Valley, Dunedin
9         NaN    Pipi Road, Whangamata, Thames-Coromandel
10 -36.437912             Athol Place, Algies Bay, Rodney
11 -36.870359            Hoya Court, Henderson, Waitakere
12 -41.241585           Strathaven Place, Atawhai, Nelson
13        NaN                                         NaN
14 -39.621293               Hart Drive, Frimley, Hastings
15 -37.742625             Wairere Drive, Pukete, Hamilton
16 -45.942122              Sussex Street, Tapanui, Clutha
17 -38.220872       Balerno Place, Tokoroa, South Waikato
18        NaN  Victoria Street, Thames, Thames-Coromandel

In [5]:
print(csv_1.dropna()) #drop the data where some values are mussing

    Index             Suburb           City  Postcode   Longitude   Latitude  \
0       1       Freemans Bay       Auckland      1011  174.748652 -36.855732
1       2          Nightcaps      Southland      9630  168.028823 -45.970300
3       4           Bay View         Napier      4104  176.871662 -39.440389
4       5          Parklands   Christchurch      8083  172.705997 -43.472699
5       6      Hamilton East       Hamilton      3216  175.305496 -37.781657
7       8            Opaheke       Papakura      2113  174.947631 -37.077401
8       9  North East Valley        Dunedin      9010  170.527081 -45.846837
10     11         Algies Bay         Rodney       920  174.745447 -36.437912
12     13            Atawhai         Nelson      7010  173.326718 -41.241585
13     14     Pleasant Point         Timaru      7903  171.122902 -44.258881
14     15            Frimley       Hastings      4120  176.832406 -39.621293
15     16        Harrowfield       Hamilton      3210  175.266597 -37.742625
17     18            Tokoroa  South Waikato      3420  175.869172 -38.220872

                                 Full Address
0       Picton Street, Freemans Bay, Auckland
1           Lyne Street, Nightcaps, Southland
3     Ferguson Street South, Bay View, Napier
4       Forest Drive, Parklands, Christchurch
5          Rochford Court, Hamilton, Hamilton
7             Rhonda Place, Opaheke, Papakura
8   Selwyn Street, North East Valley, Dunedin
10            Athol Place, Algies Bay, Rodney
12          Strathaven Place, Atawhai, Nelson
13       Runa Terrace, Pleasant Point, Timaru
14              Hart Drive, Frimley, Hastings
15            Wairere Drive, Pukete, Hamilton
17      Balerno Place, Tokoroa, South Waikato

In [7]:
csv_1.dropna(axis=1) #0--> along the row && 1 --> along the columns

,Index,Suburb,City,Postcode,Full Address
0,1,Freemans Bay,Auckland,1011,"Picton Street, Freemans Bay, Auckland"
1,2,Nightcaps,Southland,9630,"Lyne Street, Nightcaps, Southland"
2,3,Northcote,North Shore,627,"McBreen Avenue, Northcote, North Shore"
3,4,Bay View,Napier,4104,"Ferguson Street South, Bay View, Napier"
4,5,Parklands,Christchurch,8083,"Forest Drive, Parklands, Christchurch"
5,6,Hamilton East,Hamilton,3216,"Rochford Court, Hamilton, Hamilton"
6,7,Te Kuiti,Waitomo,3910,"Alexandra Street, Te Kuiti, Waitomo"
7,8,Opaheke,Papakura,2113,"Rhonda Place, Opaheke, Papakura"
8,9,North East Valley,Dunedin,9010,"Selwyn Street, North East Valley, Dunedin"
9,10,Whangamata,Thames-Coromandel,3620,"Pipi Road, Whangamata, Thames-Coromandel"
10,11,Algies Bay,Rodney,920,"Athol Place, Algies Bay, Rodney"
11,12,Henderson,Waitakere,610,"Hoya Court, Henderson, Waitakere"
12,13,Atawhai,Nelson,7010,"Strathaven Place, Atawhai, Nelson"
13,14,Pleasant Point,Timaru,7903,"Runa Terrace, Pleasant Point, Timaru"
14,15,Frimley,Hastings,4120,"Hart Drive, Frimley, Hastings"
15,16,Harrowfield,Hamilton,3210,"Wairere Drive, Pukete, Hamilton"
16,17,Tapanui,Clutha,9522,"Sussex Street, Tapanui, Clutha"
17,18,Tokoroa,South Waikato,3420,"Balerno Place, Tokoroa, South Waikato"
18,19,Thames,Thames-Coromandel,3500,"Victoria Street, Thames, Thames-Coromandel"

In [15]:
csv_1.dropna(how="any") # droop all the row where any data is missing
csv_1.dropna(how="all") # NaN show in all function

,Index,Suburb,City,Postcode,Longitude,Latitude,Full Address
0,1,Freemans Bay,Auckland,1011.0,174.748652,-36.855732,"Picton Street, Freemans Bay, Auckland"
1,2,Nightcaps,Southland,9630.0,168.028823,-45.970300,"Lyne Street, Nightcaps, Southland"
2,3,Northcote,North Shore,627.0,174.755505,NaN,"McBreen Avenue, Northcote, North Shore"
3,4,Bay View,Napier,4104.0,176.871662,-39.440389,"Ferguson Street South, Bay View, Napier"
4,5,Parklands,Christchurch,8083.0,172.705997,-43.472699,"Forest Drive, Parklands, Christchurch"
5,6,Hamilton East,Hamilton,3216.0,175.305496,-37.781657,"Rochford Court, Hamilton, Hamilton"
6,7,Te Kuiti,Waitomo,3910.0,NaN,-38.330973,"Alexandra Street, Te Kuiti, Waitomo"
7,8,Opaheke,Papakura,2113.0,174.947631,-37.077401,"Rhonda Place, Opaheke, Papakura"
8,9,North East Valley,Dunedin,9010.0,170.527081,-45.846837,"Selwyn Street, North East Valley, Dunedin"
9,10,Whangamata,Thames-Coromandel,3620.0,175.883257,NaN,"Pipi Road, Whangamata, Thames-Coromandel"
10,11,Algies Bay,Rodney,920.0,174.745447,-36.437912,"Athol Place, Algies Bay, Rodney"
11,12,Henderson,Waitakere,610.0,NaN,-36.870359,"Hoya Court, Henderson, Waitakere"
12,13,Atawhai,Nelson,7010.0,173.326718,-41.241585,"Strathaven Place, Atawhai, Nelson"
13,14,NaN,NaN,NaN,NaN,NaN,NaN
14,15,Frimley,Hastings,4120.0,176.832406,-39.621293,"Hart Drive, Frimley, Hastings"
15,16,Harrowfield,Hamilton,3210.0,175.266597,-37.742625,"Wairere Drive, Pukete, Hamilton"
16,17,Tapanui,Clutha,9522.0,NaN,-45.942122,"Sussex Street, Tapanui, Clutha"
17,18,Tokoroa,South Waikato,3420.0,175.869172,-38.220872,"Balerno Place, Tokoroa, South Waikato"
18,19,Thames,Thames-Coromandel,3500.0,175.547120,NaN,"Victoria Street, Thames, Thames-Coromandel"

In [16]:
csv_1.dropna(subset=["Longitude"]) #remove nan value at specific heading

,Index,Suburb,City,Postcode,Longitude,Latitude,Full Address
0,1,Freemans Bay,Auckland,1011.0,174.748652,-36.855732,"Picton Street, Freemans Bay, Auckland"
1,2,Nightcaps,Southland,9630.0,168.028823,-45.970300,"Lyne Street, Nightcaps, Southland"
2,3,Northcote,North Shore,627.0,174.755505,NaN,"McBreen Avenue, Northcote, North Shore"
3,4,Bay View,Napier,4104.0,176.871662,-39.440389,"Ferguson Street South, Bay View, Napier"
4,5,Parklands,Christchurch,8083.0,172.705997,-43.472699,"Forest Drive, Parklands, Christchurch"
5,6,Hamilton East,Hamilton,3216.0,175.305496,-37.781657,"Rochford Court, Hamilton, Hamilton"
7,8,Opaheke,Papakura,2113.0,174.947631,-37.077401,"Rhonda Place, Opaheke, Papakura"
8,9,North East Valley,Dunedin,9010.0,170.527081,-45.846837,"Selwyn Street, North East Valley, Dunedin"
9,10,Whangamata,Thames-Coromandel,3620.0,175.883257,NaN,"Pipi Road, Whangamata, Thames-Coromandel"
10,11,Algies Bay,Rodney,920.0,174.745447,-36.437912,"Athol Place, Algies Bay, Rodney"
12,13,Atawhai,Nelson,7010.0,173.326718,-41.241585,"Strathaven Place, Atawhai, Nelson"
14,15,Frimley,Hastings,4120.0,176.832406,-39.621293,"Hart Drive, Frimley, Hastings"
15,16,Harrowfield,Hamilton,3210.0,175.266597,-37.742625,"Wairere Drive, Pukete, Hamilton"
17,18,Tokoroa,South Waikato,3420.0,175.869172,-38.220872,"Balerno Place, Tokoroa, South Waikato"
18,19,Thames,Thames-Coromandel,3500.0,175.547120,NaN,"Victoria Street, Thames, Thames-Coromandel"

In [18]:
csv_1.dropna(inplace=True) #drop all nan value row
csv_1

,Index,Suburb,City,Postcode,Longitude,Latitude,Full Address
0,1,Freemans Bay,Auckland,1011.0,174.748652,-36.855732,"Picton Street, Freemans Bay, Auckland"
1,2,Nightcaps,Southland,9630.0,168.028823,-45.970300,"Lyne Street, Nightcaps, Southland"
3,4,Bay View,Napier,4104.0,176.871662,-39.440389,"Ferguson Street South, Bay View, Napier"
4,5,Parklands,Christchurch,8083.0,172.705997,-43.472699,"Forest Drive, Parklands, Christchurch"
5,6,Hamilton East,Hamilton,3216.0,175.305496,-37.781657,"Rochford Court, Hamilton, Hamilton"
7,8,Opaheke,Papakura,2113.0,174.947631,-37.077401,"Rhonda Place, Opaheke, Papakura"
8,9,North East Valley,Dunedin,9010.0,170.527081,-45.846837,"Selwyn Street, North East Valley, Dunedin"
10,11,Algies Bay,Rodney,920.0,174.745447,-36.437912,"Athol Place, Algies Bay, Rodney"
12,13,Atawhai,Nelson,7010.0,173.326718,-41.241585,"Strathaven Place, Atawhai, Nelson"
14,15,Frimley,Hastings,4120.0,176.832406,-39.621293,"Hart Drive, Frimley, Hastings"
15,16,Harrowfield,Hamilton,3210.0,175.266597,-37.742625,"Wairere Drive, Pukete, Hamilton"
17,18,Tokoroa,South Waikato,3420.0,175.869172,-38.220872,"Balerno Place, Tokoroa, South Waikato"

In [19]:
csv_1.dropna(thresh=1) #remove those row having single non value

,Index,Suburb,City,Postcode,Longitude,Latitude,Full Address
0,1,Freemans Bay,Auckland,1011.0,174.748652,-36.855732,"Picton Street, Freemans Bay, Auckland"
1,2,Nightcaps,Southland,9630.0,168.028823,-45.970300,"Lyne Street, Nightcaps, Southland"
3,4,Bay View,Napier,4104.0,176.871662,-39.440389,"Ferguson Street South, Bay View, Napier"
4,5,Parklands,Christchurch,8083.0,172.705997,-43.472699,"Forest Drive, Parklands, Christchurch"
5,6,Hamilton East,Hamilton,3216.0,175.305496,-37.781657,"Rochford Court, Hamilton, Hamilton"
7,8,Opaheke,Papakura,2113.0,174.947631,-37.077401,"Rhonda Place, Opaheke, Papakura"
8,9,North East Valley,Dunedin,9010.0,170.527081,-45.846837,"Selwyn Street, North East Valley, Dunedin"
10,11,Algies Bay,Rodney,920.0,174.745447,-36.437912,"Athol Place, Algies Bay, Rodney"
12,13,Atawhai,Nelson,7010.0,173.326718,-41.241585,"Strathaven Place, Atawhai, Nelson"
14,15,Frimley,Hastings,4120.0,176.832406,-39.621293,"Hart Drive, Frimley, Hastings"
15,16,Harrowfield,Hamilton,3210.0,175.266597,-37.742625,"Wairere Drive, Pukete, Hamilton"
17,18,Tokoroa,South Waikato,3420.0,175.869172,-38.220872,"Balerno Place, Tokoroa, South Waikato"

In [22]:
import pandas as pd

csv_1=pd.read_csv("C:\\Users\\91742\\OneDrive\\Desktop\\ds_august\\Pandas\\Test_new2.csv")
print(csv_1)

    Index               City  Postcode   Longitude   Latitude
0       1           Auckland    1011.0  174.748652 -36.855732
1       2          Southland    9630.0  168.028823 -45.970300
2       3        North Shore     627.0  174.755505        NaN
3       4             Napier    4104.0  176.871662 -39.440389
4       5       Christchurch    8083.0  172.705997 -43.472699
5       6           Hamilton    3216.0  175.305496 -37.781657
6       7            Waitomo    3910.0         NaN -38.330973
7       8           Papakura    2113.0  174.947631 -37.077401
8       9            Dunedin    9010.0  170.527081 -45.846837
9      10  Thames-Coromandel    3620.0  175.883257        NaN
10     11             Rodney     920.0  174.745447 -36.437912
11     12          Waitakere     610.0         NaN -36.870359
12     13             Nelson    7010.0  173.326718 -41.241585
13     14                NaN       NaN         NaN        NaN
14     15           Hastings    4120.0  176.832406 -39.621293
15     16           Hamilton    3210.0  175.266597 -37.742625
16     17             Clutha    9522.0         NaN -45.942122
17     18      South Waikato    3420.0  175.869172 -38.220872
18     19  Thames-Coromandel    3500.0  175.547120        NaN

In [ ]:
csv_1.fillna("DAKSH SOOD") #fill the NAN value with the "DAKSH SOOD"

In [24]:
csv_1.fillna({"City":"DAKSH","Postcode":"sood","Longitude":"DISHU","Latitude":"HARSHU"})
#fill particular heading nan value with given value

    Index               City Postcode   Longitude   Latitude
0       1           Auckland   1011.0  174.748652 -36.855732
1       2          Southland   9630.0  168.028823   -45.9703
2       3        North Shore    627.0  174.755505     HARSHU
3       4             Napier   4104.0  176.871662 -39.440389
4       5       Christchurch   8083.0  172.705997 -43.472699
5       6           Hamilton   3216.0  175.305496 -37.781657
6       7            Waitomo   3910.0       DISHU -38.330973
7       8           Papakura   2113.0  174.947631 -37.077401
8       9            Dunedin   9010.0  170.527081 -45.846837
9      10  Thames-Coromandel   3620.0  175.883257     HARSHU
10     11             Rodney    920.0  174.745447 -36.437912
11     12          Waitakere    610.0       DISHU -36.870359
12     13             Nelson   7010.0  173.326718 -41.241585
13     14              DAKSH     sood       DISHU     HARSHU
14     15           Hastings   4120.0  176.832406 -39.621293
15     16           Hamilton   3210.0  175.266597 -37.742625
16     17             Clutha   9522.0       DISHU -45.942122
17     18      South Waikato   3420.0  175.869172 -38.220872
18     19  Thames-Coromandel   3500.0   175.54712     HARSHU

In [25]:
csv_1.fillna(method="ffill") #replace nan value with forward filling value

C:\Users\91742\AppData\Local\Temp\ipykernel_5464\1846651122.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  csv_1.fillna(method="ffill")

    Index               City  Postcode   Longitude   Latitude
0       1           Auckland    1011.0  174.748652 -36.855732
1       2          Southland    9630.0  168.028823 -45.970300
2       3        North Shore     627.0  174.755505 -45.970300
3       4             Napier    4104.0  176.871662 -39.440389
4       5       Christchurch    8083.0  172.705997 -43.472699
5       6           Hamilton    3216.0  175.305496 -37.781657
6       7            Waitomo    3910.0  175.305496 -38.330973
7       8           Papakura    2113.0  174.947631 -37.077401
8       9            Dunedin    9010.0  170.527081 -45.846837
9      10  Thames-Coromandel    3620.0  175.883257 -45.846837
10     11             Rodney     920.0  174.745447 -36.437912
11     12          Waitakere     610.0  174.745447 -36.870359
12     13             Nelson    7010.0  173.326718 -41.241585
13     14             Nelson    7010.0  173.326718 -41.241585
14     15           Hastings    4120.0  176.832406 -39.621293
15     16           Hamilton    3210.0  175.266597 -37.742625
16     17             Clutha    9522.0  175.266597 -45.942122
17     18      South Waikato    3420.0  175.869172 -38.220872
18     19  Thames-Coromandel    3500.0  175.547120 -38.220872

In [26]:
csv_1.fillna(method="bfill") #backward filling

C:\Users\91742\AppData\Local\Temp\ipykernel_5464\1457547213.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  csv_1.fillna(method="bfill")

    Index               City  Postcode   Longitude   Latitude
0       1           Auckland    1011.0  174.748652 -36.855732
1       2          Southland    9630.0  168.028823 -45.970300
2       3        North Shore     627.0  174.755505 -39.440389
3       4             Napier    4104.0  176.871662 -39.440389
4       5       Christchurch    8083.0  172.705997 -43.472699
5       6           Hamilton    3216.0  175.305496 -37.781657
6       7            Waitomo    3910.0  174.947631 -38.330973
7       8           Papakura    2113.0  174.947631 -37.077401
8       9            Dunedin    9010.0  170.527081 -45.846837
9      10  Thames-Coromandel    3620.0  175.883257 -36.437912
10     11             Rodney     920.0  174.745447 -36.437912
11     12          Waitakere     610.0  173.326718 -36.870359
12     13             Nelson    7010.0  173.326718 -41.241585
13     14           Hastings    4120.0  176.832406 -39.621293
14     15           Hastings    4120.0  176.832406 -39.621293
15     16           Hamilton    3210.0  175.266597 -37.742625
16     17             Clutha    9522.0  175.869172 -45.942122
17     18      South Waikato    3420.0  175.869172 -38.220872
18     19  Thames-Coromandel    3500.0  175.547120        NaN

In [29]:
csv_1.fillna(method="bfill",axis=1) # see the change in 7index(travel like {<-- <-- <--})

C:\Users\91742\AppData\Local\Temp\ipykernel_5464\19136627.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  csv_1.fillna(method="bfill",axis=1)
C:\Users\91742\AppData\Local\Temp\ipykernel_5464\19136627.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  csv_1.fillna(method="bfill",axis=1)

   Index               City Postcode   Longitude   Latitude
0      1           Auckland   1011.0  174.748652 -36.855732
1      2          Southland   9630.0  168.028823   -45.9703
2      3        North Shore    627.0  174.755505        NaN
3      4             Napier   4104.0  176.871662 -39.440389
4      5       Christchurch   8083.0  172.705997 -43.472699
5      6           Hamilton   3216.0  175.305496 -37.781657
6      7            Waitomo   3910.0  -38.330973 -38.330973
7      8           Papakura   2113.0  174.947631 -37.077401
8      9            Dunedin   9010.0  170.527081 -45.846837
9     10  Thames-Coromandel   3620.0  175.883257        NaN
10    11             Rodney    920.0  174.745447 -36.437912
11    12          Waitakere    610.0  -36.870359 -36.870359
12    13             Nelson   7010.0  173.326718 -41.241585
13  14.0                NaN      NaN         NaN        NaN
14    15           Hastings   4120.0  176.832406 -39.621293
15    16           Hamilton   3210.0  175.266597 -37.742625
16    17             Clutha   9522.0  -45.942122 -45.942122
17    18      South Waikato   3420.0  175.869172 -38.220872
18    19  Thames-Coromandel   3500.0   175.54712        NaN

In [45]:
csv_1.fillna(11,inplace=True) #12 is fill at the nan space
csv_1

    Index               City  Postcode   Longitude   Latitude
0       1           Auckland    1011.0  174.748652 -36.855732
1       2          Southland    9630.0  168.028823 -45.970300
2       3        North Shore     627.0  174.755505  12.000000
3       4             Napier    4104.0  176.871662 -39.440389
4       5       Christchurch    8083.0  172.705997 -43.472699
5       6           Hamilton    3216.0  175.305496 -37.781657
6       7            Waitomo    3910.0   12.000000 -38.330973
7       8           Papakura    2113.0  174.947631 -37.077401
8       9            Dunedin    9010.0  170.527081 -45.846837
9      10  Thames-Coromandel    3620.0  175.883257  12.000000
10     11             Rodney     920.0  174.745447 -36.437912
11     12          Waitakere     610.0   12.000000 -36.870359
12     13             Nelson    7010.0  173.326718 -41.241585
13     14                 12      12.0   12.000000  12.000000
14     15           Hastings    4120.0  176.832406 -39.621293
15     16           Hamilton    3210.0  175.266597 -37.742625
16     17             Clutha    9522.0   12.000000 -45.942122
17     18      South Waikato    3420.0  175.869172 -38.220872
18     19  Thames-Coromandel    3500.0  175.547120  12.000000

In [46]:
csv_1.fillna(10,inplace=True)
csv_1

    Index               City  Postcode   Longitude   Latitude
0       1           Auckland    1011.0  174.748652 -36.855732
1       2          Southland    9630.0  168.028823 -45.970300
2       3        North Shore     627.0  174.755505  12.000000
3       4             Napier    4104.0  176.871662 -39.440389
4       5       Christchurch    8083.0  172.705997 -43.472699
5       6           Hamilton    3216.0  175.305496 -37.781657
6       7            Waitomo    3910.0   12.000000 -38.330973
7       8           Papakura    2113.0  174.947631 -37.077401
8       9            Dunedin    9010.0  170.527081 -45.846837
9      10  Thames-Coromandel    3620.0  175.883257  12.000000
10     11             Rodney     920.0  174.745447 -36.437912
11     12          Waitakere     610.0   12.000000 -36.870359
12     13             Nelson    7010.0  173.326718 -41.241585
13     14                 12      12.0   12.000000  12.000000
14     15           Hastings    4120.0  176.832406 -39.621293
15     16           Hamilton    3210.0  175.266597 -37.742625
16     17             Clutha    9522.0   12.000000 -45.942122
17     18      South Waikato    3420.0  175.869172 -38.220872
18     19  Thames-Coromandel    3500.0  175.547120  12.000000

In [51]:
print(csv_1.fillna("python",limit=2))

    Index               City  Postcode   Longitude   Latitude
0       1           Auckland    1011.0  174.748652 -36.855732
1       2          Southland    9630.0  168.028823 -45.970300
2       3        North Shore     627.0  174.755505  12.000000
3       4             Napier    4104.0  176.871662 -39.440389
4       5       Christchurch    8083.0  172.705997 -43.472699
5       6           Hamilton    3216.0  175.305496 -37.781657
6       7            Waitomo    3910.0   12.000000 -38.330973
7       8           Papakura    2113.0  174.947631 -37.077401
8       9            Dunedin    9010.0  170.527081 -45.846837
9      10  Thames-Coromandel    3620.0  175.883257  12.000000
10     11             Rodney     920.0  174.745447 -36.437912
11     12          Waitakere     610.0   12.000000 -36.870359
12     13             Nelson    7010.0  173.326718 -41.241585
13     14                 12      12.0   12.000000  12.000000
14     15           Hastings    4120.0  176.832406 -39.621293
15     16           Hamilton    3210.0  175.266597 -37.742625
16     17             Clutha    9522.0   12.000000 -45.942122
17     18      South Waikato    3420.0  175.869172 -38.220872
18     19  Thames-Coromandel    3500.0  175.547120  12.000000

In [ ]:
import pandas as pd

df = pd.read_csv('data.csv')

df.dropna(inplace = True)

print(df.to_string())

#Notice in the result that some rows have been removed (row 18, 22 and 28).

#These rows had cells with empty values.

Note: Now, the dropna(inplace = True) will NOT return a new DataFrame, but it will remove all rows containing NULL values from the original DataFrame.

In [ ]:
import pandas as pd

df = pd.read_csv('data.csv')

x = df["Calories"].mean() #median and mode

df["Calories"].fillna(x, inplace = True)

print(df.to_string())

#As you can see in row 18 and 28, the empty values from "Calories" was replaced with the mean: 304.68

In [ ]:
import pandas as pd

df = pd.read_csv('data.csv')

x = df["Calories"].mode()[0]

df["Calories"].fillna(x, inplace = True)

print(df.to_string())

#As you can see in row 18 and 28, the empty value from "Calories" was replaced with the mode: 300.0