In [1]:
import pandas as pd

Melt() -->

In [3]:
var = pd.DataFrame({"Days":[1,2,3,4,5,6],"Eng":[10,20,30,40,50,60],"Maths":[12,14,15,16,17,18]})
var

   Days  Eng  Maths
0     1   10     12
1     2   20     14
2     3   30     15
3     4   40     16
4     5   50     17
5     6   60     18

In [4]:
pd.melt(var) #for verticallu reshape

   variable  value
0      Days      1
1      Days      2
2      Days      3
3      Days      4
4      Days      5
5      Days      6
6       Eng     10
7       Eng     20
8       Eng     30
9       Eng     40
10      Eng     50
11      Eng     60
12    Maths     12
13    Maths     14
14    Maths     15
15    Maths     16
16    Maths     17
17    Maths     18

In [7]:
pd.melt(var,id_vars=["Eng"],var_name="Python",value_name="Daksh")

    Eng Python  Daksh
0    10   Days      1
1    20   Days      2
2    30   Days      3
3    40   Days      4
4    50   Days      5
5    60   Days      6
6    10  Maths     12
7    20  Maths     14
8    30  Maths     15
9    40  Maths     16
10   50  Maths     17
11   60  Maths     18