In [20]:
import pandas as pd

USing of Stack() function -->
used to Tramsform Columns into the row

In [21]:
df = pd.read_csv("Test_new2.csv",header=[0,1])
df

  Index          City Postcode   Longitude   Latitude
      1      Auckland     1011  174.748652 -36.855732
0     2     Southland     9630  168.028823 -45.970300
1     3   North Shore      627  174.755505        NaN
2     4        Napier     4104  176.871662 -39.440389
3     5  Christchurch     8083  172.705997 -43.472699

In [22]:
df.stack(level = 0) 
df

C:\Users\91742\AppData\Local\Temp\ipykernel_21724\3608386369.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df.stack(level = 0)

  Index          City Postcode   Longitude   Latitude
      1      Auckland     1011  174.748652 -36.855732
0     2     Southland     9630  168.028823 -45.970300
1     3   North Shore      627  174.755505        NaN
2     4        Napier     4104  176.871662 -39.440389
3     5  Christchurch     8083  172.705997 -43.472699

In [25]:
a =df.unstack()
a

Index      1           0               2
                       1               3
                       2               4
                       3               5
City       Auckland    0       Southland
                       1     North Shore
                       2          Napier
                       3    Christchurch
Postcode   1011        0            9630
                       1             627
                       2            4104
                       3            8083
Longitude  174.748652  0      168.028823
                       1      174.755505
                       2      176.871662
                       3      172.705997
Latitude   -36.855732  0        -45.9703
                       1             NaN
                       2      -39.440389
                       3      -43.472699
dtype: object

In [27]:
csv_1 =pd.read_csv("Test_new2.csv",header=[0,1,2])
csv_1

  Index          City Postcode   Longitude   Latitude
      1      Auckland     1011  174.748652 -36.855732
      2     Southland     9630  168.028823   -45.9703
0     3   North Shore      627  174.755505        NaN
1     4        Napier     4104  176.871662 -39.440389
2     5  Christchurch     8083  172.705997 -43.472699

In [28]:
csv_1.stack(level=2)

C:\Users\91742\AppData\Local\Temp\ipykernel_21724\3720627031.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  csv_1.stack(level=2)

             Index          City Postcode   Longitude   Latitude
                 1      Auckland     1011  174.748652 -36.855732
0 168.028823   NaN           NaN      NaN  174.755505        NaN
  2            3.0           NaN      NaN         NaN        NaN
  9630         NaN           NaN    627.0         NaN        NaN
  Southland    NaN   North Shore      NaN         NaN        NaN
1 -45.9703     NaN           NaN      NaN         NaN -39.440389
  168.028823   NaN           NaN      NaN  176.871662        NaN
  2            4.0           NaN      NaN         NaN        NaN
  9630         NaN           NaN   4104.0         NaN        NaN
  Southland    NaN        Napier      NaN         NaN        NaN
2 -45.9703     NaN           NaN      NaN         NaN -43.472699
  168.028823   NaN           NaN      NaN  172.705997        NaN
  2            5.0           NaN      NaN         NaN        NaN
  9630         NaN           NaN   8083.0         NaN        NaN
  Southland    NaN  Christchurch      NaN         NaN        NaN