# Pandas:
### 1.Pandas is a Python library used for data analysis and data manipulation.
### 2.It helps you store, clean, analyze, and visualize data easily — like an Excel sheet inside Python!

# Series and Data frames 
### 1. series -> 1d array like object , that can hold any data type(similar to col in table)
### 2. dataframe -> 2d , size mutable and potentially hetrogeneous tabular data str with labeled axes(row,col)

In [1]:
! pip install pandas

Requirement already satisfied: pandas in c:\python311\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in c:\python311\lib\site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\91742\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\python311\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\python311\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\91742\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: C:\Python311\python.exe -m pip install --upgrade pip

In [4]:
## series 
import pandas as pd
data =[1,2,3,4]
series = pd.Series(data)
print("series \n",series)

series
 0    1
1    2
2    3
3    4
dtype: int64

In [5]:
## ceate a series from dictionary elements 
data = {'a':1,'b':2,'c':3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [7]:
data = [10,20,30]
index =['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [9]:
##dataframe --> having multiple row and col
## create a dataframe from a dictionay of list

data = {
  'Name':['daksh','shruti','karan'],
  'Age':[21,20,5],
  'City':['Delhi','Nanded','Pune']
}

df = pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age    City
0   daksh   21   Delhi
1  shruti   20  Nanded
2   karan    5    Pune
<class 'pandas.core.frame.DataFrame'>

In [10]:
import numpy as np
np.array(df)

array([['daksh', 21, 'Delhi'],
       ['shruti', 20, 'Nanded'],
       ['karan', 5, 'Pune']], dtype=object)

In [12]:
## create a dataframe from a list of dictionary

data = [
  {'Name' : 'Daksh', 'Age': 21 ,'City': 'Banglore'},
  {'Name' : 'shruti', 'Age': 20 ,'City': 'Nanded'},
  {'Name' : 'Shashank', 'Age': 20 ,'City': 'Rajasthan'},
  {'Name' : 'Shagun', 'Age': 19 ,'City': 'Meerut'}
]
df = pd.DataFrame(data)
print(df)
print(type(df))

       Name  Age       City
0     Daksh   21   Banglore
1    shruti   20     Nanded
2  Shashank   20  Rajasthan
3    Shagun   19     Meerut
<class 'pandas.core.frame.DataFrame'>

In [19]:
df = pd.read_csv('C:/Users/91742/OneDrive/Desktop/TECH/Machine Learning/ds_august/Practice/Iris.csv')

df.head(5)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [21]:
df.tail(5)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [26]:

data = [
  {'Name' : 'Daksh', 'Age': 21 ,'City': 'Banglore'},
  {'Name' : 'shruti', 'Age': 20 ,'City': 'Nanded'},
  {'Name' : 'Shashank', 'Age': 20 ,'City': 'Rajasthan'},
  {'Name' : 'Shagun', 'Age': 19 ,'City': 'Meerut'}
]
df = pd.DataFrame(data)
print(df)

       Name  Age       City
0     Daksh   21   Banglore
1    shruti   20     Nanded
2  Shashank   20  Rajasthan
3    Shagun   19     Meerut

In [ ]:
### accessing data from data frame
df['Name']

0       Daksh
1      shruti
2    Shashank
3      Shagun
Name: Name, dtype: object

In [ ]:
## .loc --> label based selection (selecting data using row or column names (labels))
df.loc[0][0] # giving warning

C:\Users\91742\AppData\Local\Temp\ipykernel_13380\2527876973.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0]

'Daksh'

In [37]:
## index based selection (u selecting data using row/column position(number))
df.iloc[0][0]

C:\Users\91742\AppData\Local\Temp\ipykernel_13380\699695219.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][0]

'Daksh'

In [41]:
## Accessing a speciified element
df.at[2,'Age']

np.int64(20)

In [42]:
df.at[2,'Name']

'Shashank'

In [43]:
## accessing element using iat
df.iat[2,2]

'Rajasthan'

In [46]:
df

       Name  Age       City
0     Daksh   21   Banglore
1    shruti   20     Nanded
2  Shashank   20  Rajasthan
3    Shagun   19     Meerut

In [62]:
## data manipulation with df
df['salary']=[50000,60000,70000,10000]
df

       Name  Age       City  salary
0     Daksh   21   Banglore   50000
1    shruti   20     Nanded   60000
2  Shashank   20  Rajasthan   70000
3    Shagun   19     Meerut   10000

In [ ]:
## Remove a column by -> drop
# temprary operation
# df.drop('salary',axis=1) # for droping first we have to give the axis
df

       Name  Age       City  salary
0     Daksh   21   Banglore   50000
1    shruti   20     Nanded   60000
2  Shashank   20  Rajasthan   70000
3    Shagun   19     Meerut   10000

In [ ]:
## Remove a column by -> inplace
## parmanent operation
df.drop('salary',axis=1,inplace=True) ## remove parmanently
df

       Name  Age       City
0     Daksh   21   Banglore
1    shruti   20     Nanded
2  Shashank   20  Rajasthan
3    Shagun   19     Meerut

In [65]:
## Add age to the column
df['Age'] = df['Age']+1
df

       Name  Age       City
0     Daksh   22   Banglore
1    shruti   21     Nanded
2  Shashank   21  Rajasthan
3    Shagun   20     Meerut

In [68]:
df.drop(0,inplace = True)

In [69]:
df

       Name  Age       City
1    shruti   21     Nanded
2  Shashank   21  Rajasthan
3    Shagun   20     Meerut

In [70]:
df = pd.read_csv('C:/Users/91742/OneDrive/Desktop/TECH/Machine Learning/ds_august/Practice/Iris.csv')

df.head(5)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [73]:
# display the data types of each column
print("data types:\n",df.dtypes)

data types:
 Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [74]:
# describe the dataframe
print("statistical summary:\n",df.describe())

statistical summary:
                Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [76]:
# group by a column and perform an aggregation
grouped = df.groupby('SepalLengthCm')['SepalWidthCm'].mean()
print("Mean value by category:\n",grouped.head(5))

Mean value by category:
 SepalLengthCm
4.3    3.000000
4.4    3.033333
4.5    2.300000
4.6    3.325000
4.7    3.200000
Name: SepalWidthCm, dtype: float64