In [15]:
import pandas as pd
dis = {"a":[1,2,3,4,5,6],"b":[1,2,3,4,5,6],"c":[1,2,3,4,5,6],"d":[1,2,3,4,5,6],"e":[1,2,3,4,5,6],"f":[1,2,3,4,5,6],"g":[1,2,3,4,5,6],"h":[1,2,3,4,5,6],"i":[1,2,3,4,5,6],}
d=pd.DataFrame(dis)
print(d)
d.to_csv("Test_new2.csv",index=False)
#index=('a','b','c','d','e','f') ,,, header=[1,2,3,4]

   a  b  c  d  e  f  g  h  i
0  1  1  1  1  1  1  1  1  1
1  2  2  2  2  2  2  2  2  2
2  3  3  3  3  3  3  3  3  3
3  4  4  4  4  4  4  4  4  4
4  5  5  5  5  5  5  5  5  5
5  6  6  6  6  6  6  6  6  6

PermissionError: [Errno 13] Permission denied: 'Test_new2.csv'

CSV file(comma separated values)
-->to apply csv (var.to_csv("any file)) -->put the file in same folder

How to read csv file in python pandas-->
pd.read_csv("path\\name.csv) --> then go and take the file path-->

In [1]:
import pandas as pd
csv_1=pd.read_csv("C:\\Users\\91742\\OneDrive\\Desktop\\ds_august\\Pandas\\Test_new.csv")
print(csv_1)
print(csv_1.index)

    Index              Suburb               City  postcode   Longitude  \
0       1        Freemans Bay           Auckland      1011  174.748652
1       2           Nightcaps          Southland      9630  168.028823
2       3           Northcote        North Shore       627  174.755505
3       4            Bay View             Napier      4104  176.871662
4       5           Parklands       Christchurch      8083  172.705997
5       6       Hamilton East           Hamilton      3216  175.305496
6       7            Te Kuiti            Waitomo      3910  175.163086
7       8             Opaheke           Papakura      2113  174.947631
8       9   North East Valley            Dunedin      9010  170.527081
9      10          Whangamata  Thames-Coromandel      3620  175.883257
10     11          Algies Bay             Rodney       920  174.745447
11     12           Henderson          Waitakere       610  174.634157
12     13             Atawhai             Nelson      7010  173.326718
13     14      Pleasant Point             Timaru      7903  171.122902
14     15             Frimley           Hastings      4120  176.832406
15     16         Harrowfield           Hamilton      3210  175.266597
16     17             Tapanui             Clutha      9522  169.262758
17     18             Tokoroa      South Waikato      3420  175.869172
18     19              Thames  Thames-Coromandel      3500  175.547120
19     20  Onekawa Industrial             Napier      4110  176.875116
20     21         Brightwater             Tasman      7022  173.109791
21     22      Stewart Island          Southland      9818  168.142741
22     23             Redwood       Christchurch      8051  172.624561
23     24            Parahaki          Whangarei       112  174.343159
24     25           Dannemora            Manukau      2016  174.927840
25     26            Kawakawa          Far North       210  174.060154
26     27             Grafton           Auckland      1023  174.760742
27     28        Napier South             Napier      4110  176.903281
28     29      Timaru Central             Timaru      7910  171.249248

     Latitude                                Full Address
0  -36.855732       Picton Street, Freemans Bay, Auckland
1  -45.970300           Lyne Street, Nightcaps, Southland
2  -36.804712      McBreen Avenue, Northcote, North Shore
3  -39.440389     Ferguson Street South, Bay View, Napier
4  -43.472699       Forest Drive, Parklands, Christchurch
5  -37.781657          Rochford Court, Hamilton, Hamilton
6  -38.330973         Alexandra Street, Te Kuiti, Waitomo
7  -37.077401             Rhonda Place, Opaheke, Papakura
8  -45.846837   Selwyn Street, North East Valley, Dunedin
9  -37.219172    Pipi Road, Whangamata, Thames-Coromandel
10 -36.437912             Athol Place, Algies Bay, Rodney
11 -36.870359            Hoya Court, Henderson, Waitakere
12 -41.241585           Strathaven Place, Atawhai, Nelson
13 -44.258881        Runa Terrace, Pleasant Point, Timaru
14 -39.621293               Hart Drive, Frimley, Hastings
15 -37.742625             Wairere Drive, Pukete, Hamilton
16 -45.942122              Sussex Street, Tapanui, Clutha
17 -38.220872       Balerno Place, Tokoroa, South Waikato
18 -37.093270  Victoria Street, Thames, Thames-Coromandel
19 -39.498856             Hamilton Place, Onekawa, Napier
20 -41.377984        Longfields Road, Brightwater, Tasman
21 -46.905258  Ringaringa Road, Stewart Island, Southland
22 -43.473623          Aztec Place, Redwood, Christchurch
23 -35.720964         Memorial Drive, Parahaki, Whangarei
24 -36.925085          Kerridge Close, Dannemora, Manukau
25 -35.383953         Flaxmere Place, Kawakawa, Far North
26 -36.887168          Mount Eden Road, Grafton, Auckland
27 -39.493863          Normans Lane, Napier South, Napier
28 -44.394775     Elizabeth Place, Timaru Central, Timaru
RangeIndex(start=0, stop=29, step=1)

In [2]:
csv_2=pd.read_csv("C:\\Users\\91742\\OneDrive\\Desktop\\ds_august\\Pandas\\Test_new.csv"
                  ,nrows=5,usecols=["Suburb","City","postcode","postcode"])
#,nrows=5,

print(csv_2)

         Suburb          City  postcode
0  Freemans Bay      Auckland      1011
1     Nightcaps     Southland      9630
2     Northcote   North Shore       627
3      Bay View        Napier      4104
4     Parklands  Christchurch      8083

In [ ]:
csv_3=pd.read_csv("C:\\Users\\91742\\OneDrive\\Desktop\\ds_august\\Pandas\\Test_new.csv",skiprows=[2] )
print(csv_3)

In [6]:
import pandas as pd
csv_2=pd.read_csv("C:\\Users\\91742\\OneDrive\\Desktop\\ds_august\\Pandas\\Test_new.csv"
                  ,index_col="City") #index_col is only valid for index not for other headings!!!
print(csv_2)

                   Index              Suburb  postcode   Longitude   Latitude  \
City
Auckland               1        Freemans Bay      1011  174.748652 -36.855732
Southland              2           Nightcaps      9630  168.028823 -45.970300
North Shore            3           Northcote       627  174.755505 -36.804712
Napier                 4            Bay View      4104  176.871662 -39.440389
Christchurch           5           Parklands      8083  172.705997 -43.472699
Hamilton               6       Hamilton East      3216  175.305496 -37.781657
Waitomo                7            Te Kuiti      3910  175.163086 -38.330973
Papakura               8             Opaheke      2113  174.947631 -37.077401
Dunedin                9   North East Valley      9010  170.527081 -45.846837
Thames-Coromandel     10          Whangamata      3620  175.883257 -37.219172
Rodney                11          Algies Bay       920  174.745447 -36.437912
Waitakere             12           Henderson       610  174.634157 -36.870359
Nelson                13             Atawhai      7010  173.326718 -41.241585
Timaru                14      Pleasant Point      7903  171.122902 -44.258881
Hastings              15             Frimley      4120  176.832406 -39.621293
Hamilton              16         Harrowfield      3210  175.266597 -37.742625
Clutha                17             Tapanui      9522  169.262758 -45.942122
South Waikato         18             Tokoroa      3420  175.869172 -38.220872
Thames-Coromandel     19              Thames      3500  175.547120 -37.093270
Napier                20  Onekawa Industrial      4110  176.875116 -39.498856
Tasman                21         Brightwater      7022  173.109791 -41.377984
Southland             22      Stewart Island      9818  168.142741 -46.905258
Christchurch          23             Redwood      8051  172.624561 -43.473623
Whangarei             24            Parahaki       112  174.343159 -35.720964
Manukau               25           Dannemora      2016  174.927840 -36.925085
Far North             26            Kawakawa       210  174.060154 -35.383953
Auckland              27             Grafton      1023  174.760742 -36.887168
Napier                28        Napier South      4110  176.903281 -39.493863
Timaru                29      Timaru Central      7910  171.249248 -44.394775

                                                 Full Address
City
Auckland                Picton Street, Freemans Bay, Auckland
Southland                   Lyne Street, Nightcaps, Southland
North Shore            McBreen Avenue, Northcote, North Shore
Napier                Ferguson Street South, Bay View, Napier
Christchurch            Forest Drive, Parklands, Christchurch
Hamilton                   Rochford Court, Hamilton, Hamilton
Waitomo                   Alexandra Street, Te Kuiti, Waitomo
Papakura                      Rhonda Place, Opaheke, Papakura
Dunedin             Selwyn Street, North East Valley, Dunedin
Thames-Coromandel    Pipi Road, Whangamata, Thames-Coromandel
Rodney                        Athol Place, Algies Bay, Rodney
Waitakere                    Hoya Court, Henderson, Waitakere
Nelson                      Strathaven Place, Atawhai, Nelson
Timaru                   Runa Terrace, Pleasant Point, Timaru
Hastings                        Hart Drive, Frimley, Hastings
Hamilton                      Wairere Drive, Pukete, Hamilton
Clutha                         Sussex Street, Tapanui, Clutha
South Waikato           Balerno Place, Tokoroa, South Waikato
Thames-Coromandel  Victoria Street, Thames, Thames-Coromandel
Napier                        Hamilton Place, Onekawa, Napier
Tasman                   Longfields Road, Brightwater, Tasman
Southland          Ringaringa Road, Stewart Island, Southland
Christchurch               Aztec Place, Redwood, Christchurch
Whangarei                 Memorial Drive, Parahaki, Whangarei
Manukau                    Kerridge Close, Dannemora, Manukau
Far North                 Flaxmere Place, Kawakawa, Far North
Auckland                   Mount Eden Road, Grafton, Auckland
Napier                     Normans Lane, Napier South, Napier
Timaru                Elizabeth Place, Timaru Central, Timaru

In [7]:
import pandas as pd
csv_1=pd.read_csv("C:\\Users\\91742\\OneDrive\\Desktop\\ds_august\\Pandas\\Test_new.csv"
                  ,header=2) #heading change ho jati hai
print(csv_1)

     2           Nightcaps          Southland  9630  168.028823   -45.9703  \
0    3           Northcote        North Shore   627  174.755505 -36.804712
1    4            Bay View             Napier  4104  176.871662 -39.440389
2    5           Parklands       Christchurch  8083  172.705997 -43.472699
3    6       Hamilton East           Hamilton  3216  175.305496 -37.781657
4    7            Te Kuiti            Waitomo  3910  175.163086 -38.330973
5    8             Opaheke           Papakura  2113  174.947631 -37.077401
6    9   North East Valley            Dunedin  9010  170.527081 -45.846837
7   10          Whangamata  Thames-Coromandel  3620  175.883257 -37.219172
8   11          Algies Bay             Rodney   920  174.745447 -36.437912
9   12           Henderson          Waitakere   610  174.634157 -36.870359
10  13             Atawhai             Nelson  7010  173.326718 -41.241585
11  14      Pleasant Point             Timaru  7903  171.122902 -44.258881
12  15             Frimley           Hastings  4120  176.832406 -39.621293
13  16         Harrowfield           Hamilton  3210  175.266597 -37.742625
14  17             Tapanui             Clutha  9522  169.262758 -45.942122
15  18             Tokoroa      South Waikato  3420  175.869172 -38.220872
16  19              Thames  Thames-Coromandel  3500  175.547120 -37.093270
17  20  Onekawa Industrial             Napier  4110  176.875116 -39.498856
18  21         Brightwater             Tasman  7022  173.109791 -41.377984
19  22      Stewart Island          Southland  9818  168.142741 -46.905258
20  23             Redwood       Christchurch  8051  172.624561 -43.473623
21  24            Parahaki          Whangarei   112  174.343159 -35.720964
22  25           Dannemora            Manukau  2016  174.927840 -36.925085
23  26            Kawakawa          Far North   210  174.060154 -35.383953
24  27             Grafton           Auckland  1023  174.760742 -36.887168
25  28        Napier South             Napier  4110  176.903281 -39.493863
26  29      Timaru Central             Timaru  7910  171.249248 -44.394775

             Lyne Street, Nightcaps, Southland
0       McBreen Avenue, Northcote, North Shore
1      Ferguson Street South, Bay View, Napier
2        Forest Drive, Parklands, Christchurch
3           Rochford Court, Hamilton, Hamilton
4          Alexandra Street, Te Kuiti, Waitomo
5              Rhonda Place, Opaheke, Papakura
6    Selwyn Street, North East Valley, Dunedin
7     Pipi Road, Whangamata, Thames-Coromandel
8              Athol Place, Algies Bay, Rodney
9             Hoya Court, Henderson, Waitakere
10           Strathaven Place, Atawhai, Nelson
11        Runa Terrace, Pleasant Point, Timaru
12               Hart Drive, Frimley, Hastings
13             Wairere Drive, Pukete, Hamilton
14              Sussex Street, Tapanui, Clutha
15       Balerno Place, Tokoroa, South Waikato
16  Victoria Street, Thames, Thames-Coromandel
17             Hamilton Place, Onekawa, Napier
18        Longfields Road, Brightwater, Tasman
19  Ringaringa Road, Stewart Island, Southland
20          Aztec Place, Redwood, Christchurch
21         Memorial Drive, Parahaki, Whangarei
22          Kerridge Close, Dannemora, Manukau
23         Flaxmere Place, Kawakawa, Far North
24          Mount Eden Road, Grafton, Auckland
25          Normans Lane, Napier South, Napier
26     Elizabeth Place, Timaru Central, Timaru

In [10]:
import pandas as pd
csv_1=pd.read_csv("C:\\Users\\91742\\OneDrive\\Desktop\\ds_august\\Pandas\\Test_new.csv"
                  ,names=["daksh1","daksh2","daksh3","daksh4","daksh5","daksh6","daksh7",])
print(csv_1)

   daksh1              daksh2             daksh3    daksh4      daksh5  \
0   Index              Suburb               City  postcode   Longitude
1       1        Freemans Bay           Auckland      1011  174.748652
2       2           Nightcaps          Southland      9630  168.028823
3       3           Northcote        North Shore       627  174.755505
4       4            Bay View             Napier      4104  176.871662
5       5           Parklands       Christchurch      8083  172.705997
6       6       Hamilton East           Hamilton      3216  175.305496
7       7            Te Kuiti            Waitomo      3910  175.163086
8       8             Opaheke           Papakura      2113  174.947631
9       9   North East Valley            Dunedin      9010  170.527081
10     10          Whangamata  Thames-Coromandel      3620  175.883257
11     11          Algies Bay             Rodney       920  174.745447
12     12           Henderson          Waitakere       610  174.634157
13     13             Atawhai             Nelson      7010  173.326718
14     14      Pleasant Point             Timaru      7903  171.122902
15     15             Frimley           Hastings      4120  176.832406
16     16         Harrowfield           Hamilton      3210  175.266597
17     17             Tapanui             Clutha      9522  169.262758
18     18             Tokoroa      South Waikato      3420  175.869172
19     19              Thames  Thames-Coromandel      3500   175.54712
20     20  Onekawa Industrial             Napier      4110  176.875116
21     21         Brightwater             Tasman      7022  173.109791
22     22      Stewart Island          Southland      9818  168.142741
23     23             Redwood       Christchurch      8051  172.624561
24     24            Parahaki          Whangarei       112  174.343159
25     25           Dannemora            Manukau      2016   174.92784
26     26            Kawakawa          Far North       210  174.060154
27     27             Grafton           Auckland      1023  174.760742
28     28        Napier South             Napier      4110  176.903281
29     29      Timaru Central             Timaru      7910  171.249248

        daksh6                                      daksh7
0     Latitude                                Full Address
1   -36.855732       Picton Street, Freemans Bay, Auckland
2     -45.9703           Lyne Street, Nightcaps, Southland
3   -36.804712      McBreen Avenue, Northcote, North Shore
4   -39.440389     Ferguson Street South, Bay View, Napier
5   -43.472699       Forest Drive, Parklands, Christchurch
6   -37.781657          Rochford Court, Hamilton, Hamilton
7   -38.330973         Alexandra Street, Te Kuiti, Waitomo
8   -37.077401             Rhonda Place, Opaheke, Papakura
9   -45.846837   Selwyn Street, North East Valley, Dunedin
10  -37.219172    Pipi Road, Whangamata, Thames-Coromandel
11  -36.437912             Athol Place, Algies Bay, Rodney
12  -36.870359            Hoya Court, Henderson, Waitakere
13  -41.241585           Strathaven Place, Atawhai, Nelson
14  -44.258881        Runa Terrace, Pleasant Point, Timaru
15  -39.621293               Hart Drive, Frimley, Hastings
16  -37.742625             Wairere Drive, Pukete, Hamilton
17  -45.942122              Sussex Street, Tapanui, Clutha
18  -38.220872       Balerno Place, Tokoroa, South Waikato
19   -37.09327  Victoria Street, Thames, Thames-Coromandel
20  -39.498856             Hamilton Place, Onekawa, Napier
21  -41.377984        Longfields Road, Brightwater, Tasman
22  -46.905258  Ringaringa Road, Stewart Island, Southland
23  -43.473623          Aztec Place, Redwood, Christchurch
24  -35.720964         Memorial Drive, Parahaki, Whangarei
25  -36.925085          Kerridge Close, Dannemora, Manukau
26  -35.383953         Flaxmere Place, Kawakawa, Far North
27  -36.887168          Mount Eden Road, Grafton, Auckland
28  -39.493863          Normans Lane, Napier South, Napier
29  -44.394775     Elizabeth Place, Timaru Central, Timaru

-->to remove heading we use [header = none]
-->to give heading we use [prefix="any name"]
--> to convert int to float[dtype={"name_of_faeding":"data typr(float, int)"}]

PYTHON PANDAS FUNCTION-->
-->csv_1.index --> RangeIndex(start=0, stop=29[(n+1)value], step=1)
-->csv_1.columns --> Index(['Index', 'Suburb', 'City', 'postcode', 'Longitude', 'Latitude',
       'Full Address'],
      dtype='object') ---> all heading that r present in the csv file
--> csv_1.describe --> give count,mean,std,min,max,(25,50,75)% value --> only of numerical value
-->csv_1.head() & csv_1.tail() --> that function give top and bottom value of the file(by default it gives 5 value)-->csv_1.head(value) & csv_1.tail(value) 
-->csv_1.to_numpy()--> to convert in the form numpy

In [20]:
import pandas as pd
csv_1=pd.read_csv("C:\\Users\\91742\\OneDrive\\Desktop\\ds_august\\Pandas\\Test_new.csv")
print(csv_1)
print(csv_1.index)  #stop=n+1
print(csv_1.columns)
print(csv_1.describe()) 
print(csv_1.head()) #top 5 values
print(csv_1.tail())#lowest 5 values
print(csv_1[6:11]) #list slicing
print(type(csv_1))
print(csv_1.index.array) #to show the number in the form of array
print(csv_1.to_numpy())

[[1 'Freemans Bay' 'Auckland' 1011 174.748652 -36.855732
  'Picton Street, Freemans Bay, Auckland']
 [2 'Nightcaps' 'Southland' 9630 168.028823 -45.9703
  'Lyne Street, Nightcaps, Southland']
 [3 'Northcote' 'North Shore' 627 174.755505 -36.804712
  'McBreen Avenue, Northcote, North Shore']
 [4 'Bay View' 'Napier' 4104 176.871662 -39.440389
  'Ferguson Street South, Bay View, Napier']
 [5 'Parklands' 'Christchurch' 8083 172.705997 -43.472699
  'Forest Drive, Parklands, Christchurch']
 [6 'Hamilton East' 'Hamilton' 3216 175.305496 -37.781657
  'Rochford Court, Hamilton, Hamilton']
 [7 'Te Kuiti' 'Waitomo' 3910 175.163086 -38.330973
  'Alexandra Street, Te Kuiti, Waitomo']
 [8 'Opaheke' 'Papakura' 2113 174.947631 -37.077401
  'Rhonda Place, Opaheke, Papakura']
 [9 'North East Valley' 'Dunedin' 9010 170.527081 -45.846837
  'Selwyn Street, North East Valley, Dunedin']
 [10 'Whangamata' 'Thames-Coromandel' 3620 175.883257 -37.219172
  'Pipi Road, Whangamata, Thames-Coromandel']
 [11 'Algies Bay' 'Rodney' 920 174.745447 -36.437912
  'Athol Place, Algies Bay, Rodney']
 [12 'Henderson' 'Waitakere' 610 174.634157 -36.870359
  'Hoya Court, Henderson, Waitakere']
 [13 'Atawhai' 'Nelson' 7010 173.326718 -41.241585
  'Strathaven Place, Atawhai, Nelson']
 [14 'Pleasant Point' 'Timaru' 7903 171.122902 -44.258881
  'Runa Terrace, Pleasant Point, Timaru']
 [15 'Frimley' 'Hastings' 4120 176.832406 -39.621293
  'Hart Drive, Frimley, Hastings']
 [16 'Harrowfield' 'Hamilton' 3210 175.266597 -37.742625
  'Wairere Drive, Pukete, Hamilton']
 [17 'Tapanui' 'Clutha' 9522 169.262758 -45.942122
  'Sussex Street, Tapanui, Clutha']
 [18 'Tokoroa' 'South Waikato' 3420 175.869172 -38.220872
  'Balerno Place, Tokoroa, South Waikato']
 [19 'Thames' 'Thames-Coromandel' 3500 175.54712 -37.09327
  'Victoria Street, Thames, Thames-Coromandel']
 [20 'Onekawa Industrial' 'Napier' 4110 176.875116 -39.498856
  'Hamilton Place, Onekawa, Napier']
 [21 'Brightwater' 'Tasman' 7022 173.109791 -41.377984
  'Longfields Road, Brightwater, Tasman']
 [22 'Stewart Island' 'Southland' 9818 168.142741 -46.905258
  'Ringaringa Road, Stewart Island, Southland']
 [23 'Redwood' 'Christchurch' 8051 172.624561 -43.473623
  'Aztec Place, Redwood, Christchurch']
 [24 'Parahaki' 'Whangarei' 112 174.343159 -35.720964
  'Memorial Drive, Parahaki, Whangarei']
 [25 'Dannemora' 'Manukau' 2016 174.92784 -36.925085
  'Kerridge Close, Dannemora, Manukau']
 [26 'Kawakawa' 'Far North' 210 174.060154 -35.383953
  'Flaxmere Place, Kawakawa, Far North']
 [27 'Grafton' 'Auckland' 1023 174.760742 -36.887168
  'Mount Eden Road, Grafton, Auckland']
 [28 'Napier South' 'Napier' 4110 176.903281 -39.493863
  'Normans Lane, Napier South, Napier']
 [29 'Timaru Central' 'Timaru' 7910 171.249248 -44.394775
  'Elizabeth Place, Timaru Central, Timaru']]

In [21]:
import pandas as pd
import numpy as np

csv_9=pd.read_csv("C:\\Users\\91742\\OneDrive\\Desktop\\ds_august\\Pandas\\Test_new.csv")
var = np.asarray(csv_9) #to convert array in numpy
print(var)

[[1 'Freemans Bay' 'Auckland' 1011 174.748652 -36.855732
  'Picton Street, Freemans Bay, Auckland']
 [2 'Nightcaps' 'Southland' 9630 168.028823 -45.9703
  'Lyne Street, Nightcaps, Southland']
 [3 'Northcote' 'North Shore' 627 174.755505 -36.804712
  'McBreen Avenue, Northcote, North Shore']
 [4 'Bay View' 'Napier' 4104 176.871662 -39.440389
  'Ferguson Street South, Bay View, Napier']
 [5 'Parklands' 'Christchurch' 8083 172.705997 -43.472699
  'Forest Drive, Parklands, Christchurch']
 [6 'Hamilton East' 'Hamilton' 3216 175.305496 -37.781657
  'Rochford Court, Hamilton, Hamilton']
 [7 'Te Kuiti' 'Waitomo' 3910 175.163086 -38.330973
  'Alexandra Street, Te Kuiti, Waitomo']
 [8 'Opaheke' 'Papakura' 2113 174.947631 -37.077401
  'Rhonda Place, Opaheke, Papakura']
 [9 'North East Valley' 'Dunedin' 9010 170.527081 -45.846837
  'Selwyn Street, North East Valley, Dunedin']
 [10 'Whangamata' 'Thames-Coromandel' 3620 175.883257 -37.219172
  'Pipi Road, Whangamata, Thames-Coromandel']
 [11 'Algies Bay' 'Rodney' 920 174.745447 -36.437912
  'Athol Place, Algies Bay, Rodney']
 [12 'Henderson' 'Waitakere' 610 174.634157 -36.870359
  'Hoya Court, Henderson, Waitakere']
 [13 'Atawhai' 'Nelson' 7010 173.326718 -41.241585
  'Strathaven Place, Atawhai, Nelson']
 [14 'Pleasant Point' 'Timaru' 7903 171.122902 -44.258881
  'Runa Terrace, Pleasant Point, Timaru']
 [15 'Frimley' 'Hastings' 4120 176.832406 -39.621293
  'Hart Drive, Frimley, Hastings']
 [16 'Harrowfield' 'Hamilton' 3210 175.266597 -37.742625
  'Wairere Drive, Pukete, Hamilton']
 [17 'Tapanui' 'Clutha' 9522 169.262758 -45.942122
  'Sussex Street, Tapanui, Clutha']
 [18 'Tokoroa' 'South Waikato' 3420 175.869172 -38.220872
  'Balerno Place, Tokoroa, South Waikato']
 [19 'Thames' 'Thames-Coromandel' 3500 175.54712 -37.09327
  'Victoria Street, Thames, Thames-Coromandel']
 [20 'Onekawa Industrial' 'Napier' 4110 176.875116 -39.498856
  'Hamilton Place, Onekawa, Napier']
 [21 'Brightwater' 'Tasman' 7022 173.109791 -41.377984
  'Longfields Road, Brightwater, Tasman']
 [22 'Stewart Island' 'Southland' 9818 168.142741 -46.905258
  'Ringaringa Road, Stewart Island, Southland']
 [23 'Redwood' 'Christchurch' 8051 172.624561 -43.473623
  'Aztec Place, Redwood, Christchurch']
 [24 'Parahaki' 'Whangarei' 112 174.343159 -35.720964
  'Memorial Drive, Parahaki, Whangarei']
 [25 'Dannemora' 'Manukau' 2016 174.92784 -36.925085
  'Kerridge Close, Dannemora, Manukau']
 [26 'Kawakawa' 'Far North' 210 174.060154 -35.383953
  'Flaxmere Place, Kawakawa, Far North']
 [27 'Grafton' 'Auckland' 1023 174.760742 -36.887168
  'Mount Eden Road, Grafton, Auckland']
 [28 'Napier South' 'Napier' 4110 176.903281 -39.493863
  'Normans Lane, Napier South, Napier']
 [29 'Timaru Central' 'Timaru' 7910 171.249248 -44.394775
  'Elizabeth Place, Timaru Central, Timaru']]

In [22]:
csv_10=pd.read_csv("C:\\Users\\91742\\OneDrive\\Desktop\\ds_august\\Pandas\\Test_new.csv")
csv_10.sort_index(axis=0,ascending=False) #convert into decending order3
#'0'--> for acending acc to row && '1'--> coloumns k acc work

,Index,Suburb,City,postcode,Longitude,Latitude,Full Address
28,29,Timaru Central,Timaru,7910,171.249248,-44.394775,"Elizabeth Place, Timaru Central, Timaru"
27,28,Napier South,Napier,4110,176.903281,-39.493863,"Normans Lane, Napier South, Napier"
26,27,Grafton,Auckland,1023,174.760742,-36.887168,"Mount Eden Road, Grafton, Auckland"
25,26,Kawakawa,Far North,210,174.060154,-35.383953,"Flaxmere Place, Kawakawa, Far North"
24,25,Dannemora,Manukau,2016,174.927840,-36.925085,"Kerridge Close, Dannemora, Manukau"
23,24,Parahaki,Whangarei,112,174.343159,-35.720964,"Memorial Drive, Parahaki, Whangarei"
22,23,Redwood,Christchurch,8051,172.624561,-43.473623,"Aztec Place, Redwood, Christchurch"
21,22,Stewart Island,Southland,9818,168.142741,-46.905258,"Ringaringa Road, Stewart Island, Southland"
20,21,Brightwater,Tasman,7022,173.109791,-41.377984,"Longfields Road, Brightwater, Tasman"
19,20,Onekawa Industrial,Napier,4110,176.875116,-39.498856,"Hamilton Place, Onekawa, Napier"
18,19,Thames,Thames-Coromandel,3500,175.547120,-37.093270,"Victoria Street, Thames, Thames-Coromandel"
17,18,Tokoroa,South Waikato,3420,175.869172,-38.220872,"Balerno Place, Tokoroa, South Waikato"
16,17,Tapanui,Clutha,9522,169.262758,-45.942122,"Sussex Street, Tapanui, Clutha"
15,16,Harrowfield,Hamilton,3210,175.266597,-37.742625,"Wairere Drive, Pukete, Hamilton"
14,15,Frimley,Hastings,4120,176.832406,-39.621293,"Hart Drive, Frimley, Hastings"
13,14,Pleasant Point,Timaru,7903,171.122902,-44.258881,"Runa Terrace, Pleasant Point, Timaru"
12,13,Atawhai,Nelson,7010,173.326718,-41.241585,"Strathaven Place, Atawhai, Nelson"
11,12,Henderson,Waitakere,610,174.634157,-36.870359,"Hoya Court, Henderson, Waitakere"
10,11,Algies Bay,Rodney,920,174.745447,-36.437912,"Athol Place, Algies Bay, Rodney"
9,10,Whangamata,Thames-Coromandel,3620,175.883257,-37.219172,"Pipi Road, Whangamata, Thames-Coromandel"
8,9,North East Valley,Dunedin,9010,170.527081,-45.846837,"Selwyn Street, North East Valley, Dunedin"
7,8,Opaheke,Papakura,2113,174.947631,-37.077401,"Rhonda Place, Opaheke, Papakura"
6,7,Te Kuiti,Waitomo,3910,175.163086,-38.330973,"Alexandra Street, Te Kuiti, Waitomo"
5,6,Hamilton East,Hamilton,3216,175.305496,-37.781657,"Rochford Court, Hamilton, Hamilton"
4,5,Parklands,Christchurch,8083,172.705997,-43.472699,"Forest Drive, Parklands, Christchurch"
3,4,Bay View,Napier,4104,176.871662,-39.440389,"Ferguson Street South, Bay View, Napier"
2,3,Northcote,North Shore,627,174.755505,-36.804712,"McBreen Avenue, Northcote, North Shore"
1,2,Nightcaps,Southland,9630,168.028823,-45.970300,"Lyne Street, Nightcaps, Southland"
0,1,Freemans Bay,Auckland,1011,174.748652,-36.855732,"Picton Street, Freemans Bay, Auckland"

In [26]:
csv_11=pd.read_csv("C:\\Users\\91742\\OneDrive\\Desktop\\ds_august\\Pandas\\Test_new.csv")
csv_11["Suburb"][0]="daksh sood" # it is not a valid way to convert any index name
print(csv_11)
csv_11.loc[0,"Suburb"]="harsh sood" #valid way to convet index name
print(csv_11)

    Index              Suburb               City  postcode   Longitude  \
0       1          harsh sood           Auckland      1011  174.748652
1       2           Nightcaps          Southland      9630  168.028823
2       3           Northcote        North Shore       627  174.755505
3       4            Bay View             Napier      4104  176.871662
4       5           Parklands       Christchurch      8083  172.705997
5       6       Hamilton East           Hamilton      3216  175.305496
6       7            Te Kuiti            Waitomo      3910  175.163086
7       8             Opaheke           Papakura      2113  174.947631
8       9   North East Valley            Dunedin      9010  170.527081
9      10          Whangamata  Thames-Coromandel      3620  175.883257
10     11          Algies Bay             Rodney       920  174.745447
11     12           Henderson          Waitakere       610  174.634157
12     13             Atawhai             Nelson      7010  173.326718
13     14      Pleasant Point             Timaru      7903  171.122902
14     15             Frimley           Hastings      4120  176.832406
15     16         Harrowfield           Hamilton      3210  175.266597
16     17             Tapanui             Clutha      9522  169.262758
17     18             Tokoroa      South Waikato      3420  175.869172
18     19              Thames  Thames-Coromandel      3500  175.547120
19     20  Onekawa Industrial             Napier      4110  176.875116
20     21         Brightwater             Tasman      7022  173.109791
21     22      Stewart Island          Southland      9818  168.142741
22     23             Redwood       Christchurch      8051  172.624561
23     24            Parahaki          Whangarei       112  174.343159
24     25           Dannemora            Manukau      2016  174.927840
25     26            Kawakawa          Far North       210  174.060154
26     27             Grafton           Auckland      1023  174.760742
27     28        Napier South             Napier      4110  176.903281
28     29      Timaru Central             Timaru      7910  171.249248

     Latitude                                Full Address
0  -36.855732       Picton Street, Freemans Bay, Auckland
1  -45.970300           Lyne Street, Nightcaps, Southland
2  -36.804712      McBreen Avenue, Northcote, North Shore
3  -39.440389     Ferguson Street South, Bay View, Napier
4  -43.472699       Forest Drive, Parklands, Christchurch
5  -37.781657          Rochford Court, Hamilton, Hamilton
6  -38.330973         Alexandra Street, Te Kuiti, Waitomo
7  -37.077401             Rhonda Place, Opaheke, Papakura
8  -45.846837   Selwyn Street, North East Valley, Dunedin
9  -37.219172    Pipi Road, Whangamata, Thames-Coromandel
10 -36.437912             Athol Place, Algies Bay, Rodney
11 -36.870359            Hoya Court, Henderson, Waitakere
12 -41.241585           Strathaven Place, Atawhai, Nelson
13 -44.258881        Runa Terrace, Pleasant Point, Timaru
14 -39.621293               Hart Drive, Frimley, Hastings
15 -37.742625             Wairere Drive, Pukete, Hamilton
16 -45.942122              Sussex Street, Tapanui, Clutha
17 -38.220872       Balerno Place, Tokoroa, South Waikato
18 -37.093270  Victoria Street, Thames, Thames-Coromandel
19 -39.498856             Hamilton Place, Onekawa, Napier
20 -41.377984        Longfields Road, Brightwater, Tasman
21 -46.905258  Ringaringa Road, Stewart Island, Southland
22 -43.473623          Aztec Place, Redwood, Christchurch
23 -35.720964         Memorial Drive, Parahaki, Whangarei
24 -36.925085          Kerridge Close, Dannemora, Manukau
25 -35.383953         Flaxmere Place, Kawakawa, Far North
26 -36.887168          Mount Eden Road, Grafton, Auckland
27 -39.493863          Normans Lane, Napier South, Napier
28 -44.394775     Elizabeth Place, Timaru Central, Timaru

In [37]:
csv_12=pd.read_csv("C:\\Users\\91742\\OneDrive\\Desktop\\ds_august\\Pandas\\Test_new.csv")
print(csv_12.loc[[4,3],["postcode","Longitude"]]) # to get partiular slot of data
print(csv_12.loc[:,["postcode","Longitude"]])
print(csv_12.loc[[4,3],:])

   postcode   Longitude
4      8083  172.705997
3      4104  176.871662
    postcode   Longitude
0       1011  174.748652
1       9630  168.028823
2        627  174.755505
3       4104  176.871662
4       8083  172.705997
5       3216  175.305496
6       3910  175.163086
7       2113  174.947631
8       9010  170.527081
9       3620  175.883257
10       920  174.745447
11       610  174.634157
12      7010  173.326718
13      7903  171.122902
14      4120  176.832406
15      3210  175.266597
16      9522  169.262758
17      3420  175.869172
18      3500  175.547120
19      4110  176.875116
20      7022  173.109791
21      9818  168.142741
22      8051  172.624561
23       112  174.343159
24      2016  174.927840
25       210  174.060154
26      1023  174.760742
27      4110  176.903281
28      7910  171.249248
   Index     Suburb          City  postcode   Longitude   Latitude  \
4      5  Parklands  Christchurch      8083  172.705997 -43.472699
3      4   Bay View        Napier      4104  176.871662 -39.440389

                              Full Address
4    Forest Drive, Parklands, Christchurch
3  Ferguson Street South, Bay View, Napier

In [38]:
print(csv_12.iloc[0,1]) #row * col

Freemans Bay

In [39]:
csv_12.drop(0,axis=0)

,Index,Suburb,City,postcode,Longitude,Latitude,Full Address
1,2,Nightcaps,Southland,9630,168.028823,-45.970300,"Lyne Street, Nightcaps, Southland"
2,3,Northcote,North Shore,627,174.755505,-36.804712,"McBreen Avenue, Northcote, North Shore"
3,4,Bay View,Napier,4104,176.871662,-39.440389,"Ferguson Street South, Bay View, Napier"
4,5,Parklands,Christchurch,8083,172.705997,-43.472699,"Forest Drive, Parklands, Christchurch"
5,6,Hamilton East,Hamilton,3216,175.305496,-37.781657,"Rochford Court, Hamilton, Hamilton"
6,7,Te Kuiti,Waitomo,3910,175.163086,-38.330973,"Alexandra Street, Te Kuiti, Waitomo"
7,8,Opaheke,Papakura,2113,174.947631,-37.077401,"Rhonda Place, Opaheke, Papakura"
8,9,North East Valley,Dunedin,9010,170.527081,-45.846837,"Selwyn Street, North East Valley, Dunedin"
9,10,Whangamata,Thames-Coromandel,3620,175.883257,-37.219172,"Pipi Road, Whangamata, Thames-Coromandel"
10,11,Algies Bay,Rodney,920,174.745447,-36.437912,"Athol Place, Algies Bay, Rodney"
11,12,Henderson,Waitakere,610,174.634157,-36.870359,"Hoya Court, Henderson, Waitakere"
12,13,Atawhai,Nelson,7010,173.326718,-41.241585,"Strathaven Place, Atawhai, Nelson"
13,14,Pleasant Point,Timaru,7903,171.122902,-44.258881,"Runa Terrace, Pleasant Point, Timaru"
14,15,Frimley,Hastings,4120,176.832406,-39.621293,"Hart Drive, Frimley, Hastings"
15,16,Harrowfield,Hamilton,3210,175.266597,-37.742625,"Wairere Drive, Pukete, Hamilton"
16,17,Tapanui,Clutha,9522,169.262758,-45.942122,"Sussex Street, Tapanui, Clutha"
17,18,Tokoroa,South Waikato,3420,175.869172,-38.220872,"Balerno Place, Tokoroa, South Waikato"
18,19,Thames,Thames-Coromandel,3500,175.547120,-37.093270,"Victoria Street, Thames, Thames-Coromandel"
19,20,Onekawa Industrial,Napier,4110,176.875116,-39.498856,"Hamilton Place, Onekawa, Napier"
20,21,Brightwater,Tasman,7022,173.109791,-41.377984,"Longfields Road, Brightwater, Tasman"
21,22,Stewart Island,Southland,9818,168.142741,-46.905258,"Ringaringa Road, Stewart Island, Southland"
22,23,Redwood,Christchurch,8051,172.624561,-43.473623,"Aztec Place, Redwood, Christchurch"
23,24,Parahaki,Whangarei,112,174.343159,-35.720964,"Memorial Drive, Parahaki, Whangarei"
24,25,Dannemora,Manukau,2016,174.927840,-36.925085,"Kerridge Close, Dannemora, Manukau"
25,26,Kawakawa,Far North,210,174.060154,-35.383953,"Flaxmere Place, Kawakawa, Far North"
26,27,Grafton,Auckland,1023,174.760742,-36.887168,"Mount Eden Road, Grafton, Auckland"
27,28,Napier South,Napier,4110,176.903281,-39.493863,"Normans Lane, Napier South, Napier"
28,29,Timaru Central,Timaru,7910,171.249248,-44.394775,"Elizabeth Place, Timaru Central, Timaru"