In [1]:
import pandas as pd
csv_2=pd.read_csv("C:\\Users\\91742\\OneDrive\\Desktop\\ds_august\\Pandas\\Test_new2.csv")
print(csv_2)

    Index               City  Postcode   Longitude   Latitude
0       1           Auckland    1011.0  174.748652 -36.855732
1       2          Southland    9630.0  168.028823 -45.970300
2       3        North Shore     627.0  174.755505        NaN
3       4             Napier    4104.0  176.871662 -39.440389
4       5       Christchurch    8083.0  172.705997 -43.472699
5       6           Hamilton    3216.0  175.305496 -37.781657
6       7            Waitomo    3910.0         NaN -38.330973
7       8           Papakura    2113.0  174.947631 -37.077401
8       9            Dunedin    9010.0  170.527081 -45.846837
9      10  Thames-Coromandel    3620.0  175.883257        NaN
10     11             Rodney     920.0  174.745447 -36.437912
11     12          Waitakere     610.0         NaN -36.870359
12     13             Nelson    7010.0  173.326718 -41.241585
13     14                NaN       NaN         NaN        NaN
14     15           Hastings    4120.0  176.832406 -39.621293
15     16           Hamilton    3210.0  175.266597 -37.742625
16     17             Clutha    9522.0         NaN -45.942122
17     18      South Waikato    3420.0  175.869172 -38.220872
18     19  Thames-Coromandel    3500.0  175.547120        NaN

In [5]:
print(csv_2.fillna("python",limit=2)) #fill python upto the limit -->2

    Index               City Postcode   Longitude   Latitude
0       1           Auckland   1011.0  174.748652 -36.855732
1       2          Southland   9630.0  168.028823   -45.9703
2       3        North Shore    627.0  174.755505     python
3       4             Napier   4104.0  176.871662 -39.440389
4       5       Christchurch   8083.0  172.705997 -43.472699
5       6           Hamilton   3216.0  175.305496 -37.781657
6       7            Waitomo   3910.0      python -38.330973
7       8           Papakura   2113.0  174.947631 -37.077401
8       9            Dunedin   9010.0  170.527081 -45.846837
9      10  Thames-Coromandel   3620.0  175.883257     python
10     11             Rodney    920.0  174.745447 -36.437912
11     12          Waitakere    610.0      python -36.870359
12     13             Nelson   7010.0  173.326718 -41.241585
13     14             python   python         NaN        NaN
14     15           Hastings   4120.0  176.832406 -39.621293
15     16           Hamilton   3210.0  175.266597 -37.742625
16     17             Clutha   9522.0         NaN -45.942122
17     18      South Waikato   3420.0  175.869172 -38.220872
18     19  Thames-Coromandel   3500.0   175.54712        NaN

In [6]:
csv_2.fillna(10,inplace=True)
csv_2

    Index               City  Postcode   Longitude   Latitude
0       1           Auckland    1011.0  174.748652 -36.855732
1       2          Southland    9630.0  168.028823 -45.970300
2       3        North Shore     627.0  174.755505  10.000000
3       4             Napier    4104.0  176.871662 -39.440389
4       5       Christchurch    8083.0  172.705997 -43.472699
5       6           Hamilton    3216.0  175.305496 -37.781657
6       7            Waitomo    3910.0   10.000000 -38.330973
7       8           Papakura    2113.0  174.947631 -37.077401
8       9            Dunedin    9010.0  170.527081 -45.846837
9      10  Thames-Coromandel    3620.0  175.883257  10.000000
10     11             Rodney     920.0  174.745447 -36.437912
11     12          Waitakere     610.0   10.000000 -36.870359
12     13             Nelson    7010.0  173.326718 -41.241585
13     14                 10      10.0   10.000000  10.000000
14     15           Hastings    4120.0  176.832406 -39.621293
15     16           Hamilton    3210.0  175.266597 -37.742625
16     17             Clutha    9522.0   10.000000 -45.942122
17     18      South Waikato    3420.0  175.869172 -38.220872
18     19  Thames-Coromandel    3500.0  175.547120  10.000000

HANDALING MISSING VALUES (REPLACE AND INTERPOLATE) IN PYTHON PANDAS
replace -->chnage the particular point

In [6]:
import pandas as pd
csv_3=pd.read_csv("C:\\Users\\91742\\OneDrive\\Desktop\\ds_august\\Pandas\\Test_new2.csv")
print(csv_3)

    Index               City  Postcode   Longitude   Latitude
0       1           Auckland    1011.0  174.748652 -36.855732
1       2          Southland    9630.0  168.028823 -45.970300
2       3        North Shore     627.0  174.755505        NaN
3       4             Napier    4104.0  176.871662 -39.440389
4       5       Christchurch    8083.0  172.705997 -43.472699
5       6           Hamilton       1.0  175.305496 -37.781657
6       7            Waitomo       1.0         NaN -38.330973
7       8           Papakura       1.0  174.947631 -37.077401
8       9            Dunedin       1.0  170.527081 -45.846837
9      10  Thames-Coromandel       1.0  175.883257        NaN
10     11             Rodney       1.0  174.745447 -36.437912
11     12          Waitakere     610.0         NaN -36.870359
12     13             Nelson    7010.0  173.326718 -41.241585
13     14                NaN       NaN         NaN        NaN
14     15           Hastings    4120.0  176.832406 -39.621293
15     16           Hamilton    3210.0  175.266597 -37.742625
16     17             Clutha    9522.0         NaN -45.942122
17     18      South Waikato    3420.0  175.869172 -38.220872
18     19  Thames-Coromandel    3500.0  175.547120        NaN

In [22]:
# print(csv_3.replace(to_replace="Southland",value="daksh sood"))
# print(csv_3.replace(to_replace=1,value=69)) 
#replace --> number

    Index               City  Postcode   Longitude   Latitude
0     999           Auckland    1011.0  174.748652 -36.855732
1     999          Southland    9630.0  168.028823 -45.970300
2     999        North Shore     627.0  174.755505        NaN
3     999             Napier    4104.0  176.871662 -39.440389
4     999       Christchurch    8083.0  172.705997 -43.472699
5     999           Hamilton     999.0  175.305496 -37.781657
6     999            Waitomo     999.0         NaN -38.330973
7     999           Papakura     999.0  174.947631 -37.077401
8     999            Dunedin     999.0  170.527081 -45.846837
9      10  Thames-Coromandel     999.0  175.883257        NaN
10     11             Rodney     999.0  174.745447 -36.437912
11     12          Waitakere     610.0         NaN -36.870359
12     13             Nelson    7010.0  173.326718 -41.241585
13     14                NaN       NaN         NaN        NaN
14     15           Hastings    4120.0  176.832406 -39.621293
15     16           Hamilton    3210.0  175.266597 -37.742625
16     17             Clutha    9522.0         NaN -45.942122
17     18      South Waikato    3420.0  175.869172 -38.220872
18     19  Thames-Coromandel    3500.0  175.547120        NaN

In [26]:
csv_3.replace("[A-Za-z]","DAKSH SOOD",regex=True) #to change all values

,Index,City,Postcode,Longitude,Latitude
0,1,DAKSH SOODDAKSH SOODDAKSH SOODDAKSH SOODDAKSH ...,1011.0,174.748652,-36.855732
1,2,DAKSH SOODDAKSH SOODDAKSH SOODDAKSH SOODDAKSH ...,9630.0,168.028823,-45.970300
2,3,DAKSH SOODDAKSH SOODDAKSH SOODDAKSH SOODDAKSH ...,627.0,174.755505,NaN
3,4,DAKSH SOODDAKSH SOODDAKSH SOODDAKSH SOODDAKSH ...,4104.0,176.871662,-39.440389
4,5,DAKSH SOODDAKSH SOODDAKSH SOODDAKSH SOODDAKSH ...,8083.0,172.705997,-43.472699
5,6,DAKSH SOODDAKSH SOODDAKSH SOODDAKSH SOODDAKSH ...,1.0,175.305496,-37.781657
6,7,DAKSH SOODDAKSH SOODDAKSH SOODDAKSH SOODDAKSH ...,1.0,NaN,-38.330973
7,8,DAKSH SOODDAKSH SOODDAKSH SOODDAKSH SOODDAKSH ...,1.0,174.947631,-37.077401
8,9,DAKSH SOODDAKSH SOODDAKSH SOODDAKSH SOODDAKSH ...,1.0,170.527081,-45.846837
9,10,DAKSH SOODDAKSH SOODDAKSH SOODDAKSH SOODDAKSH ...,1.0,175.883257,NaN
10,11,DAKSH SOODDAKSH SOODDAKSH SOODDAKSH SOODDAKSH ...,1.0,174.745447,-36.437912
11,12,DAKSH SOODDAKSH SOODDAKSH SOODDAKSH SOODDAKSH ...,610.0,NaN,-36.870359
12,13,DAKSH SOODDAKSH SOODDAKSH SOODDAKSH SOODDAKSH ...,7010.0,173.326718,-41.241585
13,14,NaN,NaN,NaN,NaN
14,15,DAKSH SOODDAKSH SOODDAKSH SOODDAKSH SOODDAKSH ...,4120.0,176.832406,-39.621293
15,16,DAKSH SOODDAKSH SOODDAKSH SOODDAKSH SOODDAKSH ...,3210.0,175.266597,-37.742625
16,17,DAKSH SOODDAKSH SOODDAKSH SOODDAKSH SOODDAKSH ...,9522.0,NaN,-45.942122
17,18,DAKSH SOODDAKSH SOODDAKSH SOODDAKSH SOODDAKSH ...,3420.0,175.869172,-38.220872
18,19,DAKSH SOODDAKSH SOODDAKSH SOODDAKSH SOODDAKSH ...,3500.0,175.547120,NaN

In [28]:
csv_3.replace({"City":'[A-Z]'},22, regex=True) #change all the value of particular col

C:\Users\91742\AppData\Local\Temp\ipykernel_14680\2775520036.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  csv_3.replace({"City":'[A-Z]'},22, regex=True)

    Index  City  Postcode   Longitude   Latitude
0       1  22.0    1011.0  174.748652 -36.855732
1       2  22.0    9630.0  168.028823 -45.970300
2       3  22.0     627.0  174.755505        NaN
3       4  22.0    4104.0  176.871662 -39.440389
4       5  22.0    8083.0  172.705997 -43.472699
5       6  22.0       1.0  175.305496 -37.781657
6       7  22.0       1.0         NaN -38.330973
7       8  22.0       1.0  174.947631 -37.077401
8       9  22.0       1.0  170.527081 -45.846837
9      10  22.0       1.0  175.883257        NaN
10     11  22.0       1.0  174.745447 -36.437912
11     12  22.0     610.0         NaN -36.870359
12     13  22.0    7010.0  173.326718 -41.241585
13     14   NaN       NaN         NaN        NaN
14     15  22.0    4120.0  176.832406 -39.621293
15     16  22.0    3210.0  175.266597 -37.742625
16     17  22.0    9522.0         NaN -45.942122
17     18  22.0    3420.0  175.869172 -38.220872
18     19  22.0    3500.0  175.547120        NaN

In [33]:
csv_3.replace(1,method="ffill",limit=2,inplace=True) #inpace chnage the original date
# csv_3.replace(1,method="bfill")
csv_3

C:\Users\91742\AppData\Local\Temp\ipykernel_14680\2050383615.py:1: FutureWarning: The 'method' keyword in DataFrame.replace is deprecated and will be removed in a future version.
  csv_3.replace(1,method="ffill",limit=2,inplace=True)

    Index               City  Postcode   Longitude   Latitude
0       1           Auckland    1011.0  174.748652 -36.855732
1       2          Southland    9630.0  168.028823 -45.970300
2       3        North Shore     627.0  174.755505        NaN
3       4             Napier    4104.0  176.871662 -39.440389
4       5       Christchurch    8083.0  172.705997 -43.472699
5       6           Hamilton    8083.0  175.305496 -37.781657
6       7            Waitomo    8083.0         NaN -38.330973
7       8           Papakura    8083.0  174.947631 -37.077401
8       9            Dunedin    8083.0  170.527081 -45.846837
9      10  Thames-Coromandel       1.0  175.883257        NaN
10     11             Rodney       1.0  174.745447 -36.437912
11     12          Waitakere     610.0         NaN -36.870359
12     13             Nelson    7010.0  173.326718 -41.241585
13     14                NaN       NaN         NaN        NaN
14     15           Hastings    4120.0  176.832406 -39.621293
15     16           Hamilton    3210.0  175.266597 -37.742625
16     17             Clutha    9522.0         NaN -45.942122
17     18      South Waikato    3420.0  175.869172 -38.220872
18     19  Thames-Coromandel    3500.0  175.547120        NaN