In [4]:
import pandas as pd

var1 = pd.DataFrame({"A":[1,2,3,4],"B":[11,22,33,44]})

var2 = pd.DataFrame({"C":[12,32,43,54],"B":[11,22,33,48]})

pd.merge(var1,var2,on="B") #interchnage according to our choice

   A   B   C
0  1  11  12
1  2  22  32
2  3  33  43

var1 and var2 -->  are merge when they have 1 common element ,, if their is any uncommon number to wha tk print hoga jha tk common hoga !!!

In [10]:
pd.merge(var1,var2,how="outer",indicator=True)

     A   B     C      _merge
0  1.0  11  12.0        both
1  2.0  22  32.0        both
2  3.0  33  43.0        both
3  4.0  44   NaN   left_only
4  NaN  48  54.0  right_only

how="(outer/right/left)"

In [13]:
pd.merge(var1,var2,left_index=True,right_index=True,suffixes=("name","id")) #using index we can see any data

   A  Bname   C  Bid
0  1     11  12   11
1  2     22  32   22
2  3     33  43   33
3  4     44  54   48

CONCAT in python pandas
merging of same heading in the one row

In [14]:
#concat of two series
sr1=pd.Series([1,2,3,4])
sr2=pd.Series([11,22,33,44])

pd.concat([sr1,sr2])

0     1
1     2
2     3
3     4
0    11
1    22
2    33
3    44
dtype: int64

In [22]:
#concat of two data-frames
d1 = pd.DataFrame({"A":[1,2,3,4],"B":[11,22,33,44]})
d2 = pd.DataFrame({"A":[12,32],"B":[11,48]}) #dono ka same size ka hona zaruri hai

pd.concat([d1,d2],axis=1,join="outer",keys=["d1","d2"]) #axis = 1 (concat along the col)

  d1        d2
   A   B     A     B
0  1  11  12.0  11.0
1  2  22  32.0  48.0
2  3  33   NaN   NaN
3  4  44   NaN   NaN

join="inner/outer"

In [27]:
b1 = pd.DataFrame({"D":[12,32,45,22]})
b2 = pd.DataFrame({"A":[1,2,3,4],"C":[11,22,33,44]})


pd.concat([b1,b2])

      D    A     C
0  12.0  NaN   NaN
1  32.0  NaN   NaN
2  45.0  NaN   NaN
3  22.0  NaN   NaN
0   NaN  1.0  11.0
1   NaN  2.0  22.0
2   NaN  3.0  33.0
3   NaN  4.0  44.0