In [8]:
import pandas as pd


-->data arrangment and reshaping

In [9]:
var = pd.DataFrame({"Days":[1,1,1,1,2,2],
                    "student_Name":["daksh","karan","harshu","khushi","sunaina","nitish"]
                    ,"Eng":[10,20,30,40,50,60],"Maths":[12,14,15,16,17,18]})
var

   Days student_Name  Eng  Maths
0     1        daksh   10     12
1     1        karan   20     14
2     1       harshu   30     15
3     1       khushi   40     16
4     2      sunaina   50     17
5     2       nitish   60     18

In [10]:
var.pivot(index="Days",columns="student_Name") #two arrgumnet r compulsary

               Eng                                    Maths               \
student_Name daksh harshu karan khushi nitish sunaina daksh harshu karan
Days
1             10.0   30.0  20.0   40.0    NaN     NaN  12.0   15.0  14.0
2              NaN    NaN   NaN    NaN   60.0    50.0   NaN    NaN   NaN


student_Name khushi nitish sunaina
Days
1              16.0    NaN     NaN
2               NaN   18.0    17.0

In [11]:
var.pivot_table(index="student_Name",columns="Days",aggfunc = "mean") #mean , count , max , sum , min

               Eng       Maths
Days             1     2     1     2
student_Name
daksh         10.0   NaN  12.0   NaN
harshu        30.0   NaN  15.0   NaN
karan         20.0   NaN  14.0   NaN
khushi        40.0   NaN  16.0   NaN
nitish         NaN  60.0   NaN  18.0
sunaina        NaN  50.0   NaN  17.0

In [12]:
var.pivot_table(index="student_Name",columns="Days",aggfunc = "sum",margins=True)

                Eng             Maths
Days              1      2  All     1     2 All
student_Name
daksh          10.0    NaN   10  12.0   NaN  12
harshu         30.0    NaN   30  15.0   NaN  15
karan          20.0    NaN   20  14.0   NaN  14
khushi         40.0    NaN   40  16.0   NaN  16
nitish          NaN   60.0   60   NaN  18.0  18
sunaina         NaN   50.0   50   NaN  17.0  17
All           100.0  110.0  210  57.0  35.0  92